local ls = require('luasnip')
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets('yaml', {
  s('k8ns', t({
    '---',
    'apiVersion: v1',
    'kind: Namespace',
    'metadata:',
    '  name: FIXME',
  })),
  s('k8secret', t({
    '---',
    'apiVersion: v1',
    'kind: Secret',
    'metadata:',
    '  name: FIXME-secret',
    '  namespace: FIXME',
    'data:',
    '  FIXME_KEY: FIXME_VALUE',
    '  FIXME_KEY: FIXME_VALUE',
  })),
  s('k8dep', t({
    '---',
    'apiVersion: apps/v1',
    'kind: Deployment',
    'metadata:',
    '  name: FIXME',
    '  labels:',
    '    app: FIXME',
    'spec:',
    '  replicas: FIXME',
    '  selector:',
    '    matchLabels:',
    '      app: FIXME',
    '  template:',
    '    metadata:',
    '      labels:',
    '        app: FIXME',
    '    spec:',
    '      containers:',
    '        - name: FIXME',
    '          image: FIXME',
    '          ports:',
    '            - containerPort: FIXME',
  })),
  s('k8svc', t({
    '---',
    'apiVersion: v1',
    'kind: Service',
    'metadata:',
    '  name: FIXME-internal-svc',
    'spec:',
    '  selector:',
    '    app: FIXME',
    '  ports:',
    '    - port: FIXME',
    '      targetPort: FIXME',
  })),
  s('k8ing', t({
    '---',
    'apiVersion: networking.k8s.io/v1',
    'kind: Ingress',
    'metadata:',
    '  name: FIXME-outbound-svc',
    '  namespace: FIXME',
    'spec:',
    '  ingressClassName: nginx',
    '  rules:',
    '    - host: FIXME.fritz.box',
    '      http:',
    '        paths:',
    '        - path: /',
    '          pathType: Prefix',
    '          backend:',
    '            service:',
    '              name: FIXME-internal-svc',
    '              port:',
    '                number: FIXME',
    '    - host: FIXME.indieandmore.photography',
    '      http:',
    '        paths:',
    '        - path: /',
    '          pathType: Prefix',
    '          backend:',
    '            service:',
    '              name: FIXME-internal-svc',
    '              port:',
    '                number: FIXME',
  })),
})
